In [1]:
import pandas as pd

In [4]:
dnn_data = pd.read_csv('../submissions/tfidf_dnn_submission.csv.gz')
lr_data = pd.read_csv('../submissions/logistic_regression_tfidf_submission.csv.gz')
gru_data = pd.read_csv('../submissions/more_features_pooled_gru_fasttext_submission.csv.gz')

In [5]:
dnn_data.head()

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,9.655016e-01,9.448158e-02,7.810668e-01,0.027007,6.865299e-01,0.076246
1,0000247867823ef7,1.613027e-07,5.122585e-07,6.876261e-09,0.000010,1.524862e-07,0.000012
2,00013b17ad220c46,1.573193e-02,8.921552e-04,1.448410e-03,0.001264,3.364397e-03,0.002687
3,00017563c3f7919a,5.915506e-07,1.026754e-06,2.386093e-08,0.000015,4.234203e-07,0.000020
4,00017695ad8997eb,4.094907e-07,8.212137e-07,1.627938e-08,0.000013,3.093305e-07,0.000017

In [10]:
new_df = dnn_data.copy()
new_df.loc[:, ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]] = 0
new_df.head()

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,0,0,0,0,0,0
1,0000247867823ef7,0,0,0,0,0,0
2,00013b17ad220c46,0,0,0,0,0,0
3,00017563c3f7919a,0,0,0,0,0,0
4,00017695ad8997eb,0,0,0,0,0,0

In [15]:
_classes = ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]

for _class in _classes:
    new_df.loc[:, _class] = (dnn_data.loc[:, _class] + lr_data.loc[:, _class] + gru_data.loc[:, _class] )/3

In [16]:
new_df.head()

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,0.985771,0.269466,0.920263,0.028403,0.825101,0.227484
1,0000247867823ef7,0.003275,0.001082,0.001986,0.000577,0.003094,0.001243
2,00013b17ad220c46,0.017600,0.001612,0.005253,0.000993,0.007390,0.002458
3,00017563c3f7919a,0.001267,0.000699,0.001124,0.000372,0.001351,0.000304
4,00017695ad8997eb,0.014415,0.000831,0.003683,0.000716,0.004324,0.000939

In [18]:
new_df.to_csv('../submissions/3stack_submission.csv.gz', index=False, compression="gzip")